name: HelloBroadcaster
main: HelloBroadcaster\Main
version: 1.0.2
api: [3.0.0-ALPHA12]
load: POSTWORLD
author: TheDeibo, ratchetgame98
description: Add a little romance to your server!

commands:
  hbw
    decription: "Broadcasts that you said hello"
    usage: "/hbw <Usage here>"
    aliases: [hbw, hello]
